apiVersion: v1
kind: Service
metadata:
  name: {{ include "registration-bb-et.fullname" . }}
  labels:
    {{- include "registration-bb-et.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "registration-bb-et.selectorLabels" . | nindent 4 }}
